services:
  postgres:
    image: postgres:16-alpine
    container_name: wb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wb_user
      POSTGRES_PASSWORD: wb
      POSTGRES_DB: wb_orders
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/adapter/db/migrations:/docker-entrypoint-initdb.d:ro
volumes:
  pgdata: